# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zkp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tzkp.proto\x12\x08zkp_auth\"7\n\x0fRegisterRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\n\n\x02y1\x18\x02 \x01(\x03\x12\n\n\x02y2\x18\x03 \x01(\x03\"\x12\n\x10RegisterResponse\"F\n\x1e\x41uthenticationChallengeRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\n\n\x02r1\x18\x02 \x01(\x03\x12\n\n\x02r2\x18\x03 \x01(\x03\"=\n\x1f\x41uthenticationChallengeResponse\x12\x0f\n\x07\x61uth_id\x18\x01 \x01(\t\x12\t\n\x01\x63\x18\x02 \x01(\x03\"9\n\x1b\x41uthenticationAnswerRequest\x12\x0f\n\x07\x61uth_id\x18\x01 \x01(\t\x12\t\n\x01s\x18\x02 \x01(\x03\"2\n\x1c\x41uthenticationAnswerResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\"X\n\x1a\x41syncAuthenticationRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\n\n\x02r1\x18\x02 \x01(\x03\x12\n\n\x02r2\x18\x03 \x01(\x03\x12\t\n\x01\x63\x18\x04 \x01(\x03\x12\t\n\x01s\x18\x05 \x01(\x03\x32\x99\x03\n\x04\x41uth\x12\x43\n\x08Register\x12\x19.zkp_auth.RegisterRequest\x1a\x1a.zkp_auth.RegisterResponse\"\x00\x12k\n\x19VerifyAuthenticationAsync\x12$.zkp_auth.AsyncAuthenticationRequest\x1a&.zkp_auth.AuthenticationAnswerResponse\"\x00\x12v\n\x1d\x43reateAuthenticationChallenge\x12(.zkp_auth.AuthenticationChallengeRequest\x1a).zkp_auth.AuthenticationChallengeResponse\"\x00\x12g\n\x14VerifyAuthentication\x12%.zkp_auth.AuthenticationAnswerRequest\x1a&.zkp_auth.AuthenticationAnswerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zkp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=23
  _globals['_REGISTERREQUEST']._serialized_end=78
  _globals['_REGISTERRESPONSE']._serialized_start=80
  _globals['_REGISTERRESPONSE']._serialized_end=98
  _globals['_AUTHENTICATIONCHALLENGEREQUEST']._serialized_start=100
  _globals['_AUTHENTICATIONCHALLENGEREQUEST']._serialized_end=170
  _globals['_AUTHENTICATIONCHALLENGERESPONSE']._serialized_start=172
  _globals['_AUTHENTICATIONCHALLENGERESPONSE']._serialized_end=233
  _globals['_AUTHENTICATIONANSWERREQUEST']._serialized_start=235
  _globals['_AUTHENTICATIONANSWERREQUEST']._serialized_end=292
  _globals['_AUTHENTICATIONANSWERRESPONSE']._serialized_start=294
  _globals['_AUTHENTICATIONANSWERRESPONSE']._serialized_end=344
  _globals['_ASYNCAUTHENTICATIONREQUEST']._serialized_start=346
  _globals['_ASYNCAUTHENTICATIONREQUEST']._serialized_end=434
  _globals['_AUTH']._serialized_start=437
  _globals['_AUTH']._serialized_end=846
# @@protoc_insertion_point(module_scope)
